name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: npm run test

  merge:
    needs: [lint, test]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Fail if lint or tests failed
        run: exit 1
        if: failure()
